spring:
  profiles:
    active: local
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/oscar

server:
  port: 8081

application:
  repositoryDir: /tmp/oscar

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.springframework.data: WARN
    com.oscar.controller: WARN