spring:
  profiles:
    active: local

server:
  port: 8081

application:
  repositoryDir: /tmp/oscar/repositories

logging:
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    com.codescoop.crawler: WARN